---
- hosts: local
  roles:
    - role: setup
      become: yes
      tags:
        - setup

    - role: install/dotfiles
      tags:
        - dotfiles

    - role: install/iosevka
      tags:
        - iosevka
      when: install_iosevka

    - role: install/stylua
      tags:
        - stylua
      when: install_stylua

    - role: post
      tags:
        - post
