---
- name: Clone dotfiles repo
  git:
    repo: "https://github.com/notchtc/dotfiles"
    dest: "{{ dotfiles_home }}"
    recursive: yes
    force: yes

- name: Symlink dotfiles
  file:
    src: "{{ dotfiles_home }}/{{ item.src }}"
    dest: "{{ user_home }}/{{ item.dst }}"
    state: link
    follow: no
    force: yes
  with_items:
    - { src: "fonts/.config/fontconfig", dst: ".config/fontconfig" }
    - { src: "foot/.config/foot", dst: ".config/foot" }
    - { src: "gem/.config/gem", dst: ".config/gem" }
    - { src: "nvim/.config/nvim", dst: ".config/nvim" }
    - { src: "x11/.config/X11", dst: ".config/X11" }
    - { src: "zathura/.config/zathura", dst: ".config/zathura" }
    - { src: "zsh/.zshenv", dst: ".zshenv" }
    - { src: "zsh/.config/zsh", dst: ".config/zsh" }
