---
- name: Clone dotfiles repo
  git:
    repo: "{{ dotfiles }}"
    dest: "{{ dotfiles_home }}"
    recursive: yes
    force: yes

- name: Symlink dotfiles
  shell:
    cmd: "stow -v */"
    chdir: "{{ dotfiles_home }}"
  register: stow
  changed_when: stow.stdout | length > 0
