---
- name: RPM Fusion
  when:
    - ansible_os_family == 'RedHat'
    - enable_rpm_fusion
  block:
    - name: Add RPM Fusion free key
      rpm_key:
        state: present
        key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-{{ redhat_os }}-{{ fusion_key }}"

    - name: Add RPM Fusion nonfree key
      rpm_key:
        state: present
        key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-{{ redhat_os }}-{{ fusion_key }}"

    - name: Add RPM fusion repositories
      dnf:
        name:
          - "https://mirrors.rpmfusion.org/free/{{ redhat_os }}/rpmfusion-free-release-{{ redhat_version }}.noarch.rpm"
          - "https://mirrors.rpmfusion.org/nonfree/{{ redhat_os }}/rpmfusion-nonfree-release-{{ redhat_version }}.noarch.rpm"

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: Install packages related with the rice
  package:
    name: "{{ packages }}"
    state: present

- name: Install personal packages
  package:
    name: "{{ personal_packages }}"
    state: present
  when: install_personal

- name: Set shell
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: "/usr/bin/{{ shell }}"

- name: Set graphical target
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
  when: ansible_service_mgr == 'systemd'
