---
- name: Add RPM Fusion free key
  rpm_key:
    state: present
    key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"

- name: Add RPM Fusion nonfree key
  rpm_key:
    state: present
    key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"

- name: Add RPM fusion repositories
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: Install packages
  package:
    name: "{{ packages }}"
    state: present

- name: Set shell
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: "/usr/bin/zsh"

- name: Set graphical target
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
  register: graphical
